from django.urls import path
from . import views
from . import views_phase2 as vp2

urlpatterns = [
    # ---- Phase 2: Finance depth ----
    path('finance-hub/', vp2.finance_hub, name='finance_hub'),
    path('finance-hub/invoice/create/', vp2.invoice_create, name='invoice_create'),
    path('finance-hub/invoice/<int:pk>/send/', vp2.invoice_send, name='invoice_send'),
    path('finance-hub/invoice/<int:pk>/receipt/', vp2.receipt_add, name='receipt_add'),
    path('finance-hub/invoice/<int:pk>/credit/', vp2.credit_note_add, name='credit_note_add'),
    path('finance-hub/payout/create/', vp2.payout_run_create, name='payout_run_create'),
    path('finance-hub/payout/<int:pk>/submit/', vp2.payout_run_submit, name='payout_run_submit'),
    path('finance-hub/month/lock/', vp2.month_lock, name='month_lock'),
    path('finance-hub/month/reopen/', vp2.month_reopen, name='month_reopen'),
    path('finance-hub/incentive/save/', vp2.incentive_save, name='incentive_save'),
    # ---- Phase 2: Operations subflows ----
    path('leads/<int:pk>/ops/valuation/', vp2.ops_valuation_add, name='ops_valuation_add'),
    path('leads/<int:pk>/ops/buyout/', vp2.ops_buyout_add, name='ops_buyout_add'),
    path('leads/<int:pk>/ops/noc/', vp2.ops_noc_add, name='ops_noc_add'),
    path('leads/<int:pk>/ops/transfer/', vp2.ops_transfer_add, name='ops_transfer_add'),
    # ---- Phase 2: Partners depth ----
    path('partners/<int:pk>/commission/', vp2.partner_commission_save, name='partner_commission_save'),
    path('partners/statements/', vp2.partner_statements, name='partner_statements'),
    path('partners/statements/generate/', vp2.partner_statements_generate, name='partner_statements_generate'),
    # ---- Phase 2: Automation ----
    path('automation/', vp2.automation_list, name='automation_list'),
    path('automation/save/', vp2.automation_save, name='automation_save'),
    path('automation/<int:pk>/toggle/', vp2.automation_toggle, name='automation_toggle'),
    # ---- Phase 2: HR ----
    path('hr/', vp2.hr_home, name='hr_home'),
    path('hr/checkin/', vp2.attendance_checkin, name='attendance_checkin'),
    path('hr/checkout/', vp2.attendance_checkout, name='attendance_checkout'),
    path('hr/leave/', vp2.leave_request, name='leave_request'),
    path('hr/leave/<int:pk>/decide/', vp2.leave_decide, name='leave_decide'),
    path('hr/target/', vp2.target_save, name='target_save'),
    # ---- Phase 2: Compliance/Admin depth ----
    path('settings/retention/', vp2.retention_save, name='retention_save'),
    path('custom-fields/', vp2.custom_fields_page, name='custom_fields_page'),
    path('custom-fields/<int:pk>/toggle/', vp2.custom_field_toggle, name='custom_field_toggle'),
    path('settings/custom-field/', vp2.custom_field_save, name='custom_field_save'),
    # ---- Phase 2: Reporting ----
    path('reports/forecast/view/', vp2.forecast, name='forecast'),
    path('reports/builder/', vp2.report_builder, name='report_builder'),
    # ---- Phase 2: scaffolded completions ----
    path('templates/', vp2.template_studio, name='template_studio'),
    path('templates/save/', vp2.template_save, name='template_save'),
    path('access-review/', vp2.access_review, name='access_review'),
    path('leads/<int:pk>/ubo/', vp2.ubo_add, name='ubo_add'),
    path('leads/<int:pk>/referral/', vp2.client_referral_add, name='client_referral_add'),
    path('leads/<int:pk>/dsr/export/', vp2.dsr_export, name='dsr_export'),
    path('leads/<int:pk>/dsr/anonymize/', vp2.dsr_anonymize, name='dsr_anonymize'),
    path('leads/<int:pk>/upload-link/', vp2.upload_token_create, name='upload_token_create'),
    path('upload/<str:token>/', vp2.public_upload, name='public_upload'),
    path('finance-hub/payout/<int:pk>/execute/', vp2.payout_execute, name='payout_execute'),
    path('finance-hub/incentive/compute/', vp2.incentive_compute, name='incentive_compute'),

    path('login/', views.CRMLoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('', views.dashboard, name='dashboard'),
    path('search/', views.global_search, name='global_search'),
    path('my-day/', views.my_day, name='my_day'),
    path('api/web-to-lead/', views.web_to_lead, name='web_to_lead'),
    path('api/meta/leadgen/', views.meta_leadgen, name='meta_leadgen'),
    path('calls/log/', views.log_call, name='log_call'),
    path('calls/history/', views.call_history, name='call_history'),
    path('calls/<int:pk>/edit/', views.call_edit, name='call_edit'),
    path('leads/<int:pk>/not-interested/', views.lead_not_interested, name='lead_not_interested'),
    path('notifications/', views.notifications_list, name='notifications_list'),
    path('notifications/read-all/', views.notifications_read_all, name='notifications_read_all'),
    path('notifications/<int:pk>/open/', views.notification_open, name='notification_open'),

    path('leads/', views.lead_list, name='lead_list'),
    path('leads/new/', views.lead_create, name='lead_create'),
    path('leads/import/', views.lead_import, name='lead_import'),
    path('leads/import/undo/', views.lead_import_undo, name='lead_import_undo'),
    path('leads/recycle-bin/', views.recycle_bin, name='recycle_bin'),
    path('leads/<int:pk>/restore/deleted/', views.lead_restore_deleted, name='lead_restore_deleted'),
    path('leads/<int:pk>/purge/', views.lead_purge, name='lead_purge'),
    path('tasks/<int:pk>/restore/', views.task_restore, name='task_restore'),
    path('documents/<int:pk>/restore/', views.document_restore, name='document_restore'),
    path('leads/export/', views.lead_export, name='lead_export'),
    path('leads/bulk/', views.lead_bulk, name='lead_bulk'),
    path('leads/pipeline/', views.lead_pipeline, name='lead_pipeline'),
    path('leads/sources/', views.lead_sources, name='lead_sources'),
    path('leads/lost/', views.lost_leads, name='lost_leads'),
    path('leads/meta/', views.meta_leads, name='meta_leads'),
    path('leads/<int:pk>/', views.lead_detail, name='lead_detail'),
    path('clients/<int:pk>/', views.client_360, name='client_360'),
    path('clients/<int:pk>/consent/', views.consent_update, name='consent_update'),
    path('leads/<int:pk>/edit/', views.lead_edit, name='lead_edit'),
    path('leads/<int:pk>/delete/', views.lead_delete, name='lead_delete'),
    path('leads/<int:pk>/stage/', views.lead_stage_update, name='lead_stage_update'),
    path('leads/<int:pk>/kyc/', views.lead_kyc, name='lead_kyc'),
    path('leads/<int:pk>/nurture/', views.lead_nurture, name='lead_nurture'),
    path('leads/<int:pk>/escalate/', views.lead_escalate, name='lead_escalate'),
    path('views/save/', views.saved_view_create, name='saved_view_create'),
    path('views/<int:pk>/delete/', views.saved_view_delete, name='saved_view_delete'),
    path('notification-prefs/', views.notification_prefs, name='notification_prefs'),
    path('assignment-rules/', views.assignment_rules, name='assignment_rules'),
    path('leads/<int:pk>/screening/', views.lead_screening, name='lead_screening'),
    path('leads/<int:pk>/risk/', views.lead_risk, name='lead_risk'),
    path('leads/<int:pk>/kyc-override/', views.lead_kyc_override, name='lead_kyc_override'),
    path('leads/<int:pk>/suspicion/', views.suspicion_raise, name='suspicion_raise'),
    path('compliance/', views.compliance_workspace, name='compliance_workspace'),
    path('compliance/suspicion/<int:pk>/', views.suspicion_update, name='suspicion_update'),
    path('compliance/dsr/new/', views.dsr_create, name='dsr_create'),
    path('compliance/dsr/<int:pk>/', views.dsr_update, name='dsr_update'),
    path('leads/<int:pk>/assign/', views.lead_assign, name='lead_assign'),
    path('leads/<int:pk>/disbursed-date/', views.lead_disbursed_date, name='lead_disbursed_date'),
    path('leads/<int:pk>/followup/add/', views.followup_add, name='followup_add'),
    path('leads/<int:pk>/handover/', views.lead_handover, name='lead_handover'),
    path('leads/<int:pk>/ops-assign/', views.ops_assign, name='ops_assign'),
    path('leads/<int:pk>/ops-hold/', views.ops_hold, name='ops_hold'),
    path('leads/<int:pk>/processing/', views.lead_processing, name='lead_processing'),
    path('leads/<int:pk>/query/add/', views.query_add, name='query_add'),
    path('leads/<int:pk>/query/<int:qid>/', views.query_update, name='query_update'),
    path('ops/', views.ops_queue, name='ops_queue'),
    path('leads/<int:pk>/bank-app/save/', views.bankapp_save, name='bankapp_save'),
    path('leads/<int:pk>/bank-app/<int:app_id>/delete/', views.bankapp_delete, name='bankapp_delete'),
    path('leads/<int:pk>/note/', views.lead_note_add, name='lead_note_add'),
    path('leads/<int:pk>/documents/upload/', views.lead_document_upload, name='lead_document_upload'),
    path('leads/<int:pk>/restore/', views.lead_restore, name='lead_restore'),
    path('leads/<int:pk>/pipeline-month/', views.lead_pipeline_month, name='lead_pipeline_month'),
    path('leads/sources/toggle/', views.source_toggle, name='source_toggle'),

    path('customization/', views.customization_list, name='customization_list'),
    path('customization/export/', views.customization_export, name='customization_export'),
    path('customization/add/<int:pk>/', views.customization_add, name='customization_add'),
    path('customization/<int:pk>/update/', views.customization_update, name='customization_update'),
    path('customization/<int:pk>/remove/', views.customization_remove, name='customization_remove'),

    path('tasks/', views.task_list, name='task_list'),
    path('tasks/overdue/', views.overdue_tasks, name='overdue_tasks'),
    path('tasks/new/', views.task_create, name='task_create'),
    path('tasks/export/', views.task_export, name='task_export'),
    path('tasks/<int:pk>/complete/', views.task_complete, name='task_complete'),
    path('tasks/<int:pk>/delete/', views.task_delete, name='task_delete'),

    path('banks/', views.bank_list, name='bank_list'),
    path('banks/new/', views.bank_create, name='bank_create'),
    path('banks/export/', views.bank_export, name='bank_export'),
    path('banks/<int:pk>/edit/', views.bank_edit, name='bank_edit'),
    path('banks/<int:pk>/toggle/', views.bank_toggle, name='bank_toggle'),
    path('banks/<int:pk>/delete/', views.bank_delete, name='bank_delete'),

    path('advisors/', views.advisor_list, name='advisor_list'),
    path('advisors/export/', views.advisor_export, name='advisor_export'),
    path('advisors/<int:pk>/', views.advisor_detail, name='advisor_detail'),

    path('partners/', views.partner_list, name='partner_list'),
    path('partners/new/', views.partner_create, name='partner_create'),
    path('approvals/', views.approvals_list, name='approvals_list'),
    path('approvals/<int:pk>/decide/', views.approval_decide, name='approval_decide'),
    path('partners/export/', views.partner_export, name='partner_export'),
    path('partners/<int:pk>/edit/', views.partner_edit, name='partner_edit'),
    path('partners/<int:pk>/assign/', views.partner_assign, name='partner_assign'),
    path('partners/<int:pk>/delete/', views.partner_delete, name='partner_delete'),

    path('documents/', views.document_list, name='document_list'),
    path('documents/export/', views.document_export, name='document_export'),
    path('documents/<int:pk>/delete/', views.document_delete, name='document_delete'),
    path('documents/<int:pk>/<str:action>/', views.document_action, name='document_action'),

    path('finance/', views.finance, name='finance'),
    path('finance/export/', views.finance_export, name='finance_export'),
    path('reports/', views.reports, name='reports'),
    path('reports/export/', views.report_export, name='report_export'),
    path('reports/<str:key>/', views.report_view, name='report_view'),

    path('users/', views.user_list, name='user_list'),
    path('users/new/', views.user_create, name='user_create'),
    path('users/export/', views.user_export, name='user_export'),
    path('users/<int:pk>/edit/', views.user_edit, name='user_edit'),
    path('users/<int:pk>/access/', views.user_access, name='user_access'),
    path('users/<int:pk>/delete/', views.user_delete, name='user_delete'),

    path('audit/', views.audit_log, name='audit_log'),
    path('roles/', views.role_list, name='role_list'),
    path('roles/save/', views.role_perm_save, name='role_perm_save'),
    path('settings/', views.settings_view, name='settings_view'),
    path('settings/save/', views.settings_save, name='settings_save'),
    path('settings/rules/', views.settings_rules_save, name='settings_rules_save'),
    path('settings/state/', views.settings_state_save, name='settings_state_save'),
]
