# Generated by Django 5.0.6 on 2026-07-18 17:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signrequest',
            name='sig_h',
            field=models.FloatField(default=9),
        ),
        migrations.AddField(
            model_name='signrequest',
            name='sig_page',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='signrequest',
            name='sig_w',
            field=models.FloatField(default=24),
        ),
        migrations.AddField(
            model_name='signrequest',
            name='sig_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signrequest',
            name='sig_y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signrequest',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='signrequest',
            name='signer_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
