# Generated by Django 5.0.6 on 2026-07-19 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0002_signrequest_sig_h_signrequest_sig_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='signrequest',
            name='fields',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
