# Generated by Django 5.0.6 on 2026-09-02 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esign', '0003_signrequest_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='esign/')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('fields', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docs', to='esign.signrequest')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
