# Generated by Django 5.0.6 on 2026-06-29 17:35

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('bank_type', models.CharField(choices=[('Conventional', 'Conventional'), ('Islamic', 'Islamic')], default='Conventional', max_length=20)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(default='Active', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ReferralPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('company', models.CharField(blank=True, max_length=160)),
                ('organization', models.CharField(blank=True, max_length=160)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emirates_id', models.CharField(blank=True, max_length=40)),
                ('passport_no', models.CharField(blank=True, max_length=40)),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_no', models.CharField(blank=True, max_length=60)),
                ('iban', models.CharField(blank=True, max_length=60)),
                ('partner_type', models.CharField(default='Real Estate Agency', max_length=60)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('agreement', models.FileField(blank=True, null=True, upload_to='partners/')),
                ('kyc_doc', models.FileField(blank=True, null=True, upload_to='partners/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('CEO', 'CEO / Managing Director'), ('SALES_DIRECTOR', 'Sales Director'), ('OPS_MANAGER', 'Mortgage Operations Manager'), ('ADVISOR', 'Mortgage Advisor'), ('ACCOUNTANT', 'Accountant / Finance Officer')], default='ADVISOR', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('department', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(default='Active', max_length=20)),
                ('target_calls', models.PositiveIntegerField(default=0)),
                ('target_submissions', models.PositiveIntegerField(default=0)),
                ('target_partners', models.PositiveIntegerField(default=0)),
                ('target_disbursement', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('nationality', models.CharField(blank=True, max_length=60)),
                ('property_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('ltv', models.PositiveIntegerField(default=80)),
                ('loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('source', models.CharField(choices=[('Google Ads', 'Google Ads'), ('Meta Ads', 'Meta Ads'), ('Referral Partner', 'Referral Partner'), ('Website', 'Website'), ('Walk-in', 'Walk-in'), ('Cold Calling', 'Cold Calling')], default='Website', max_length=40)),
                ('stage', models.CharField(choices=[('Lead Received', 'Lead Received'), ('Documents Pending', 'Documents Pending'), ('Documents Complete', 'Documents Complete'), ('Logged In', 'Logged In'), ('Under Review', 'Under Review'), ('Pre-Approved', 'Pre-Approved'), ('Valuation', 'Valuation'), ('Valuation Received', 'Valuation Received'), ('FOL Initiated', 'FOL Initiated'), ('FOL Issued', 'FOL Issued'), ('FOL Signing Fixed', 'FOL Signing Fixed'), ('FOL Signed', 'FOL Signed'), ('Under Disbursement', 'Under Disbursement'), ('Disbursed', 'Disbursed'), ('Property Transfer Scheduled', 'Property Transfer Scheduled'), ('Property Transfer', 'Property Transfer'), ('Property Transferred', 'Property Transferred'), ('Declined', 'Declined')], default='Lead Received', max_length=40)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('lost_reason', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advisor', models.ForeignKey(blank=True, limit_choices_to={'role': 'ADVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to=settings.AUTH_USER_MODEL)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.bank')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('Uploaded', 'Uploaded'), ('Pending Review', 'Pending Review'), ('Verified', 'Verified'), ('Rejected', 'Rejected'), ('Missing', 'Missing')], default='Pending Review', max_length=20)),
                ('uploaded_by', models.CharField(default='Customer', max_length=60)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('task_type', models.CharField(choices=[('Documents', 'Documents'), ('Bank Follow-up', 'Bank Follow-up'), ('Valuation', 'Valuation'), ('Customer Call', 'Customer Call'), ('FOL', 'FOL'), ('Disbursement', 'Disbursement'), ('Application', 'Application')], default='Documents', max_length=30)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='crm.lead')),
            ],
        ),
    ]
