# Generated by Django 5.0.6 on 2026-07-10 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_appsetting_leadsourcestate_bank_commission_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_rm', models.CharField(blank=True, max_length=120)),
                ('cp', models.CharField(blank=True, max_length=120)),
                ('slab', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('broker_pct', models.DecimalField(decimal_places=2, default=80, max_digits=5)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customization', to='crm.lead')),
            ],
            options={
                'ordering': ['-added_at'],
            },
        ),
    ]
