# Generated by Django 5.0.6 on 2026-07-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_customization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customization',
            name='vat_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
    ]
