# Generated by Django 5.0.6 on 2026-07-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_leadaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='disbursed_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
