# Generated by Django 5.0.6 on 2026-07-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_document_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
    ]
