# Generated by Django 5.0.6 on 2026-07-18 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_lead_is_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('outcome', models.CharField(choices=[('Interested', 'Interested'), ('Not Interested', 'Not Interested'), ('No Answer', 'No Answer'), ('Callback', 'Callback'), ('Busy', 'Busy')], default='No Answer', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
