# Generated by Django 5.0.6 on 2026-07-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='consent_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_sms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='score',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
