# Generated by Django 5.0.6 on 2026-07-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='first_contact_due',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='sla_notified',
            field=models.BooleanField(default=False),
        ),
    ]
