# Generated by Django 5.0.6 on 2026-07-19 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_lead_first_contact_due_lead_first_contacted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='expiry_notified',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='document',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
