# Generated by Django 5.0.6 on 2026-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_lead_deleted_at_lead_deleted_by_lead_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='outcome',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
