# Generated by Django 5.0.6 on 2026-07-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_task_completed_at_task_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='kyc_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Rejected', 'Rejected')], default='Pending', max_length=10),
        ),
    ]
