# Generated by Django 5.0.6 on 2026-07-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_lead_kyc_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
