# Generated by Django 5.0.6 on 2026-07-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_document_is_current_document_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='eligibility_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='eligible',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
