# Generated by Django 5.0.6 on 2026-07-19 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0023_auditevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='case_number',
            field=models.CharField(blank=True, db_index=True, max_length=30),
        ),
        migrations.CreateModel(
            name='BankApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Pre-Approved', 'Pre-Approved'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Withdrawn', 'Withdrawn')], default='Draft', max_length=20)),
                ('reference_no', models.CharField(blank=True, max_length=60)),
                ('requested_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sanctioned_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('interest_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decision_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.bank')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_applications', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_applications', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
