# Generated by Django 5.0.6 on 2026-07-19 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_followup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='team',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin (IT)'), ('CEO', 'CEO / Managing Director'), ('SALES_DIRECTOR', 'Sales Director'), ('TEAM_LEADER', 'Sales Team Leader'), ('OPS_MANAGER', 'Mortgage Operations Manager'), ('OPS_EXECUTIVE', 'Operations Executive'), ('ADVISOR', 'Mortgage Advisor'), ('TELECALLER', 'Telecaller / Pre-Sales'), ('ACCOUNTANT', 'Accountant / Finance Officer'), ('HR_EXECUTIVE', 'HR Executive'), ('COMPLIANCE', 'Compliance Officer'), ('MARKETING', 'Marketing Executive'), ('AUDITOR', 'External Auditor (Read-only)')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin (IT)'), ('CEO', 'CEO / Managing Director'), ('SALES_DIRECTOR', 'Sales Director'), ('TEAM_LEADER', 'Sales Team Leader'), ('OPS_MANAGER', 'Mortgage Operations Manager'), ('OPS_EXECUTIVE', 'Operations Executive'), ('ADVISOR', 'Mortgage Advisor'), ('TELECALLER', 'Telecaller / Pre-Sales'), ('ACCOUNTANT', 'Accountant / Finance Officer'), ('HR_EXECUTIVE', 'HR Executive'), ('COMPLIANCE', 'Compliance Officer'), ('MARKETING', 'Marketing Executive'), ('AUDITOR', 'External Auditor (Read-only)')], default='ADVISOR', max_length=20),
        ),
    ]
