# Generated by Django 5.0.6 on 2026-07-19 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_document_deleted_at_document_deleted_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_seq', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
