# Generated by Django 5.0.6 on 2026-07-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_casesequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='silence_notified',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
