# Generated by Django 5.0.6 on 2026-07-19 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_lead_silence_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mobile', models.CharField(blank=True, db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('nationality', models.CharField(blank=True, max_length=60)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('employer', models.CharField(blank=True, max_length=160)),
                ('lifecycle', models.CharField(choices=[('Lead', 'Lead'), ('Applicant', 'Applicant'), ('Active Client', 'Active Client'), ('Closed Client', 'Closed Client'), ('Advocate', 'Advocate')], default='Lead', max_length=20)),
                ('consent_call', models.BooleanField(default=False)),
                ('consent_sms', models.BooleanField(default=False)),
                ('consent_whatsapp', models.BooleanField(default=False)),
                ('consent_email', models.BooleanField(default=False)),
                ('do_not_contact', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='crm.client'),
        ),
    ]
