# Generated by Django 5.0.6 on 2026-07-19 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_client_lead_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='handed_over',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='handover_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='handover_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='hold_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='hold_review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='ops_hold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='ops_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ops_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
