# Generated by Django 5.0.6 on 2026-07-20 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_lead_handed_over_lead_handover_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='edd_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='edd_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='pep_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Clear', 'Clear'), ('Hit', 'Hit')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='risk_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='risk_rating',
            field=models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='sanctions_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Clear', 'Clear'), ('Hit', 'Hit')], default='Pending', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='screened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='screened_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screened_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='screening_evidence',
            field=models.FileField(blank=True, null=True, upload_to='screening/'),
        ),
        migrations.CreateModel(
            name='DataSubjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=120)),
                ('request_type', models.CharField(choices=[('Access', 'Access'), ('Correction', 'Correction'), ('Deletion', 'Deletion')], default='Access', max_length=15)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Rejected', 'Rejected')], default='Open', max_length=15)),
                ('detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dsrs', to='crm.client')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_dsrs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspicionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved')], default='Open', max_length=15)),
                ('resolution', models.TextField(blank=True)),
                ('goaml_ref', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspicions', to='crm.client')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suspicions', to='crm.lead')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_suspicions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
