# Generated by Django 5.0.6 on 2026-07-20 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0033_lead_edd_complete_lead_edd_required_lead_pep_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('Call', 'Call'), ('SMS', 'SMS'), ('WhatsApp', 'WhatsApp'), ('Email', 'Email')], max_length=12)),
                ('granted', models.BooleanField(default=True)),
                ('source', models.CharField(choices=[('Lead form', 'Lead form'), ('Verbal', 'Verbal'), ('Web form', 'Web form'), ('Import', 'Import'), ('Unsubscribe', 'Unsubscribe'), ('Manual', 'Manual')], default='Manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consent_log', to='crm.client')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_log', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
