# Generated by Django 5.0.6 on 2026-07-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0034_consentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sla_warned',
            field=models.BooleanField(default=False),
        ),
    ]
