# Generated by Django 5.0.6 on 2026-07-20 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0035_lead_sla_warned'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('Partner Activation', 'Partner Activation'), ('Fee Waiver', 'Fee Waiver'), ('Payout Run', 'Payout Run'), ('Leave', 'Leave'), ('Month Reopen', 'Month Reopen'), ('Template Publish', 'Template Publish'), ('Lost-Reason Override', 'Lost-Reason Override')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('target_model', models.CharField(blank=True, max_length=40)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('approver_role', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_decisions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
