# Generated by Django 5.0.6 on 2026-07-20 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0036_approvalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='fol_emi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lead',
            name='fol_fixed_period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='fol_fixed_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='lead',
            name='fol_offer_validity',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='fol_processing_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='fol_rate_type',
            field=models.CharField(blank=True, choices=[('', '—'), ('Fixed', 'Fixed'), ('Variable', 'Variable')], max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='fol_tenor_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='fol_variable_index',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='lead',
            name='insurance_policy_no',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='lead',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='lead',
            name='preapproval_validity_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='rework_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='title_deed_number',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='lead',
            name='valuation_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='lead',
            name='valuation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='valuation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='valuer_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='BankQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_type', models.CharField(blank=True, max_length=60)),
                ('description', models.TextField()),
                ('owner_side', models.CharField(choices=[('Advisor', 'Advisor'), ('Ops', 'Ops')], default='Ops', max_length=10)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Answered', 'Answered'), ('Closed', 'Closed')], default='Open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='crm.bankapplication')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_queries', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
