# Generated by Django 5.0.6 on 2026-07-20 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0037_document_rejection_reason_lead_fol_emi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='edd_ceo_ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='edd_source_of_funds',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='edd_source_of_wealth',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='kyc_override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='kyc_override_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_overrides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='kyc_override_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='kyc_override_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
