# Generated by Django 5.0.6 on 2026-07-22 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_lead_edd_ceo_ack_lead_edd_source_of_funds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='nurture_until',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='daily_lead_cap',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='out_of_office',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AssignmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('match_source', models.CharField(blank=True, max_length=40)),
                ('min_loan', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('max_loan', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('action', models.CharField(choices=[('round_robin', 'Round-robin (least loaded)'), ('user', 'Specific user')], default='round_robin', max_length=20)),
                ('active', models.BooleanField(default=True)),
                ('action_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SavedView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(default='Leads', max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('querystring', models.CharField(blank=True, max_length=500)),
                ('shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('muted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_prefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
