# Generated by Django 5.0.6 on 2026-07-26 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0039_lead_nurture_until_user_daily_lead_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
