# Generated by Django 5.0.6 on 2026-08-04 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_calllog_follow_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpartner',
            name='advisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ADVISOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_partners', to=settings.AUTH_USER_MODEL),
        ),
    ]
