# Generated by Django 5.0.6 on 2026-08-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0041_referralpartner_advisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='reminded',
            field=models.BooleanField(default=False),
        ),
    ]
