# Generated by Django 5.0.6 on 2026-08-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_followup_reminded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Documents', 'Documents'), ('Bank Follow-up', 'Bank Follow-up'), ('Valuation', 'Valuation'), ('Customer Call', 'Customer Call'), ('Follow-up', 'Follow-up'), ('FOL', 'FOL'), ('Disbursement', 'Disbursement'), ('Application', 'Application')], default='Documents', max_length=30),
        ),
    ]
