# Generated by Django 5.0.6 on 2026-08-12 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_alter_task_task_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='meta_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
