# Generated by Django 5.0.6 on 2026-08-12 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0044_lead_meta_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='meta_data',
        ),
        migrations.CreateModel(
            name='MetaLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leadgen_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('mobile', models.CharField(blank=True, max_length=60)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('campaign', models.CharField(blank=True, max_length=200)),
                ('form_id', models.CharField(blank=True, max_length=64)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
