# Generated by Django 5.0.6 on 2026-08-15 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_automationrule_incentivescheme_leavetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='custom',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ClientReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referred_name', models.CharField(max_length=160)),
                ('referred_mobile', models.CharField(blank=True, max_length=60)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('converted_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='crm.lead')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('referrer_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_made', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('inapp', 'In-app'), ('email', 'Email'), ('whatsapp', 'WhatsApp'), ('doc', 'Document')], default='inapp', max_length=12)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('milestone_stage', models.CharField(blank=True, max_length=40)),
                ('auto_send', models.BooleanField(default=False)),
                ('published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.approvalrequest')),
            ],
        ),
        migrations.CreateModel(
            name='UBO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('share_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('id_number', models.CharField(blank=True, max_length=60)),
                ('nationality', models.CharField(blank=True, max_length=60)),
                ('is_pep', models.BooleanField(default=False)),
                ('screened', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubos', to='crm.lead')),
            ],
        ),
        migrations.CreateModel(
            name='UploadToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_tokens', to='crm.lead')),
            ],
        ),
    ]
