# Generated by Django 5.0.6 on 2026-09-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0052_outlookaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('Lead Received', 'Lead Received'), ('Documents Pending', 'Documents Pending'), ('Documents Complete', 'Documents Complete'), ('Logged In', 'Logged In'), ('Under Review', 'Under Review'), ('Pre-Approved', 'Pre-Approved'), ('Valuation', 'Valuation'), ('Valuation Received', 'Valuation Received'), ('FOL Initiated', 'FOL Initiated'), ('FOL Issued', 'FOL Issued'), ('FOL Signing Fixed', 'FOL Signing Fixed'), ('FOL Signed', 'FOL Signed'), ('Under Disbursement', 'Under Disbursement'), ('Disbursed', 'Disbursed'), ('Property Transfer Scheduled', 'Property Transfer Scheduled'), ('Property Transfer', 'Property Transfer'), ('Property Transferred', 'Property Transferred'), ('Declined', 'Declined'), ('Rejected', 'Rejected'), ('Not Proceeding', 'Not Proceeding')], default='Lead Received', max_length=40),
        ),
    ]
