# Generated by Django 5.0.6 on 2026-09-04 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0053_alter_lead_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=254)),
                ('smtp_host', models.CharField(default='smtpout.secureserver.net', max_length=120)),
                ('smtp_port', models.PositiveIntegerField(default=465)),
                ('imap_host', models.CharField(default='imap.secureserver.net', max_length=120)),
                ('imap_port', models.PositiveIntegerField(default=993)),
                ('password_enc', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='email_account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
